/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRecommendRouteImport } from './routes/_app/recommend'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppNetworkRouteImport } from './routes/_app/network'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppGraphRouteImport } from './routes/_app/graph'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAskRouteImport } from './routes/_app/ask'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRecommendRoute = AppRecommendRouteImport.update({
  id: '/recommend',
  path: '/recommend',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworkRoute = AppNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppGraphRoute = AppGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAskRoute = AppAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/ask': typeof AppAskRoute
  '/dashboard': typeof AppDashboardRoute
  '/graph': typeof AppGraphRoute
  '/home': typeof AppHomeRoute
  '/network': typeof AppNetworkRoute
  '/profile': typeof AppProfileRoute
  '/recommend': typeof AppRecommendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/ask': typeof AppAskRoute
  '/dashboard': typeof AppDashboardRoute
  '/graph': typeof AppGraphRoute
  '/home': typeof AppHomeRoute
  '/network': typeof AppNetworkRoute
  '/profile': typeof AppProfileRoute
  '/recommend': typeof AppRecommendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/ask': typeof AppAskRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/graph': typeof AppGraphRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/network': typeof AppNetworkRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/recommend': typeof AppRecommendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/ask'
    | '/dashboard'
    | '/graph'
    | '/home'
    | '/network'
    | '/profile'
    | '/recommend'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/ask'
    | '/dashboard'
    | '/graph'
    | '/home'
    | '/network'
    | '/profile'
    | '/recommend'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/onboarding'
    | '/_app/ask'
    | '/_app/dashboard'
    | '/_app/graph'
    | '/_app/home'
    | '/_app/network'
    | '/_app/profile'
    | '/_app/recommend'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/recommend': {
      id: '/_app/recommend'
      path: '/recommend'
      fullPath: '/recommend'
      preLoaderRoute: typeof AppRecommendRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/network': {
      id: '/_app/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AppNetworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/graph': {
      id: '/_app/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof AppGraphRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ask': {
      id: '/_app/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AppAskRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAskRoute: typeof AppAskRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGraphRoute: typeof AppGraphRoute
  AppHomeRoute: typeof AppHomeRoute
  AppNetworkRoute: typeof AppNetworkRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRecommendRoute: typeof AppRecommendRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAskRoute: AppAskRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGraphRoute: AppGraphRoute,
  AppHomeRoute: AppHomeRoute,
  AppNetworkRoute: AppNetworkRoute,
  AppProfileRoute: AppProfileRoute,
  AppRecommendRoute: AppRecommendRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
